#!/bin/bash

mkdir -p tmp

# hack around docco's belief that comments are only denoted by line prefixes
# rather than some combination of prefix and suffix by removing
# trailing comments
cp experiment.js tmp/experiment.js
sed -e "s/-->//" even-odd.html > tmp/even-odd.html
sed -e "s/*\///" style.css > tmp/style.css

docco --languages languages.json --output docs tmp/experiment.js tmp/even-odd.html tmp/style.css

rm -rf tmp
